from win32api import GetSystemMetrics

Width = GetSystemMetrics(0)
Height = GetSystemMetrics(1)

#configurações Gerais
WIDTH = Width
HEIGHT = Height

PRIMARY_COLOR = [255,255,255]
SECONDARY_COLOR = [51,51,51]
BG_COLOR = [12, 149, 225]

TILE_SIZE = 64

# x -- bloquinho que o personagem vai pisar
# p -- vai ser o personagem
# "  " -- vai ser o espaço que representa o nada
# c -- vai ser as latas de lixo 
# A -- sera o bonus

TILE_SIZE = 64
MAP0 = [
'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
'XXXXXXXXXXXXXXXXX XXXX           XXXXXX',
'X                 XXXX XXXXXXXXX XXXXXX',
'XX XXXXXXXXXXXXXX XXXX XXXXXXXXX XXXXXX',
'XX XXXXXXXXXXXXXX P    XXXXXXXXX   CXXX',
'XC XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX',
'XX     XXXXXXXXX    XXXXXXXXXXXXXXXXXXX',
'XX XXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX',
'XX XXXA          XXXXXXX     CXXXXXXXXX',
'XX XXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX',
'XX XXXXXCXXXXXXX XXXXXXX XXXXXXXXXXXXXX',
'XX XXXXX XXXXXXX         XXXXXXXXXXXXXX',
'XX       XXXXXXXAXXXXXXXXXXXXXXXXXXXXXX',
'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',]

MAP1 = [
'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
'XXXXXXXXXXXX        XXXXXXX   CXXXXXXXX',
'XXXCXXXXXXXXAXXXXXX XXX     XXXXXXXXXXX',
'XXX XXXXXXXX XXXXXX XXX XXXXXXX   CXXXX',
'XXX XXXXXXXX XXXXXX XXX XXXXXXX XXXXXXX',
'XXX XXXXXXXX XXXX      XXXXXXX XXXXXXX',
'XXX XXXXXXXX XXXX XXXXX XXXXXXX XXXXXXX',
'XXX XXXXXXXX XXXX XXXXX XXXXX   XXXXXXX',
'XXX XXXXXXXX XXXXCXXXXX XXXXX XXXXXXXXX',
'XXX XXXXXXXX XXXXXXXXXX XXXXX XXXXXXXXX',
'XXX   XXXXXX XXXXXXXXXX XXXXX XXXXXXXXX',
'XXXXX XXXXXX XXXXXXXXXX      AXXXXXXXXX',
'XXXXXP       XXXXXXXXXXXXXXXXXXXXXXXXXX',
'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',]

MAP2 = [
'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
'XXXXXXX      CX X   X   X           PXX',
'XXXXXXX XXXX      X   X   X XXXXXXXX XX',
'XXXXXXX XXXXXXXXXXXXXXXXXXX XXXX     XX',
'XXXXXXX XXXXXXXXXXXXXXX     XXXXXXXXXXX',
'XXXXXXX XXXXXXXXXXXXXXXX XX XXXXXXXXXXX',
'XXXC    XXXXXXXXXXXXXXXX XX XXXXXXXXXXX',
'XXXXXXXXXXXXXXXXXXXXXXXX XX  CXXXXXXXXX',
'XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX',
'XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX',
'XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX',
'XXXXXXXXXXXXXXXXXXXCXXXXAXXXXXXXXXXXXXX',
'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',]